### ISSUE TITLE
React Mic: The recording red dot still shows after recording stops + Recorded audio has no sound

### ISSUE THREAD

**Issue by ishansan38** [hackingbeauty/react-mic#64]
This Issue has been raised before and the reply was to upgrade. I am using 12.4 right now but am facing the same issue. The red dot does not disappear even was stopping to record. This happens randomly. Any suggestions?

**Comment by ishansan38** [comment]
Update: 'getUserMedia supported' from MicrophoneRecorder.js gets printed twice, so I am guessing, even though I am stopping it, it is not actually getting stopped. This happens randomly.

**Comment by hackingbeauty** [comment]
Resolved.

**Comment by Morsmetus** [comment]
Where is the resolved code? I still can not get rid of the red dot if I unmount the component in the middle of recording. It has to call onStop callback to stop but if record state is false it will still continue to listen to microphone.

**Comment by hackingbeauty** [comment]
@Morsmetus when you use [Voice Record Pro](https://voicerecordpro.com/) to record...are you still noticing a red dot after recording has stopped?
